services:
  polarag_trainer:
    container_name: prg_trainer
    image: pytorch/pytorch:2.6.0-cuda12.4-cudnn9-devel
    shm_size: 128g
    env_file: .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./trainer_entrypoint.sh:/app/entrypoint.sh
    ports:
      - ${TRAINER_PORT}:${TRAINER_PORT}
    working_dir: /app
    command: [ "bash", "/app/entrypoint.sh" ]